// Picks up articles that have blog_body generated by the admin dashboard
// (blog_body IS NOT NULL AND note_draft_url IS NULL) and pushes each one
// to note.com as a draft via Playwright. Runs locally on the Mac that
// has auth/note-state.json.
//
// Usage: npx tsx scripts/publish-queued.ts [--limit 1] [--dry-run]
import fs from 'node:fs';
import path from 'node:path';
import { createClient } from '@supabase/supabase-js';
import { generateCoverImage } from '../src/lib/blog/cover-image';
import { publishToNoteDraft } from '../src/lib/blog/note-publisher';
import type { Database, NewsArticle } from '../src/lib/database.types';

function loadDotenv(file = '.env.local') {
  if (!fs.existsSync(file)) return;
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}

loadDotenv();

const DRY_RUN = process.argv.includes('--dry-run') || process.env.BLOG_DRY_RUN === '1';
const limitArg = process.argv.indexOf('--limit');
const LIMIT = limitArg >= 0 ? Number(process.argv[limitArg + 1]) : 5;

async function main() {
  const supabase = createClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );

  const { data, error } = await supabase
    .from('news_articles')
    .select('*')
    .is('note_draft_url', null)
    .not('blog_body', 'is', null)
    .order('published_at', { ascending: false, nullsFirst: false })
    .limit(LIMIT);
  if (error) throw error;
  if (!data || data.length === 0) {
    console.log('No queued articles (blog_body generated but not published). Nothing to do.');
    return;
  }

  console.log(`Found ${data.length} queued article(s).`);

  for (const article of data as NewsArticle[]) {
    console.log(`\n— ${article.title.slice(0, 80)}`);
    console.log(`  Source: ${article.source_name} | ${article.source_url}`);

    const title = article.blog_title ?? article.title;
    const body = article.blog_body!;

    console.log('  Generating cover image (Nano Banana)…');
    const { pngBuffer, model: coverModel } = await generateCoverImage({
      title,
      tags: article.tags,
      summary: article.ai_summary,
    });
    console.log(`  ✓ ${pngBuffer.length.toLocaleString()} bytes, model ${coverModel}`);

    const stamp = new Date().toISOString().slice(0, 10);
    const dir = path.join('drafts', `${stamp}_${article.id.slice(0, 8)}`);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'post.md'), `# ${title}\n\n${body}\n`);
    fs.writeFileSync(path.join(dir, 'cover.png'), pngBuffer);

    if (DRY_RUN) {
      console.log(`  [dry-run] Skipping note.com upload. Local draft → ${dir}`);
      continue;
    }

    // blog_body already contains hashtags appended by the admin generate API.
    const result = await publishToNoteDraft({
      title,
      body,
      hashtags: [],
      coverPng: pngBuffer,
    });
    console.log(`  ✓ draft URL: ${result.draftUrl}`);

    await supabase
      .from('news_articles')
      .update({ note_draft_url: result.draftUrl } as never)
      .eq('id', article.id);
    console.log('  ✓ note_draft_url written');
  }

  console.log('\n✅ Done.');
}

main().catch((e) => {
  console.error('[publish-queued] FATAL:', e);
  process.exit(1);
});
